services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    container_name: database_mysql
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    networks:
      - network-local

  app:
    restart: unless-stopped
    #image: ubuntu:21.04
    build:
      context: .
      dockerfile: docker/app.docker
    ports:
      - "80:80"
      - "443:443"
    container_name: app
    volumes:
      - type: bind
        source: ./app
        target: /app
    command: [ "/usr/bin/supervisord" ]
    networks:
      - network-local
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/rabbitmq/rabbitmq-local.docker
    environment:
      RABBITMQ_DEFAULT_USER: 'cyberclick'
      RABBITMQ_DEFAULT_PASS: 'lvd2009'
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbitmq
    networks:
      - network-local

  mailcatcher:
    container_name: mailcatcher
    restart: unless-stopped
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - network-local


networks:
  network-local:
